version: "3"
services:
  frontti:
    image: aapokar/frontdeploy
    ports:
      - 5000:5000
    container_name: fordeploy
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower
